version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    environment:
      - POSTGRES_DB=inrush
      - POSTGRES_USER=inrush
      - POSTGRES_PASSWORD=inrush
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inrush"]
      interval: 5s
      timeout: 5s
      retries: 5

  runtime:
    build:
      context: .
      dockerfile: apps/runtime/Dockerfile
    volumes:
      - ./apps/runtime:/app
      - runtime-data:/data
    ports:
      - "3000:3000"  # WebSocket API
      - "2222:2222"  # PLC communication
    environment:
      - GO_ENV=development
      - INRUSH_DATA_DIR=/data
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_NAME=inrush
      - DB_USER=inrush
      - DB_PASSWORD=inrush
    depends_on:
      timescaledb:
        condition: service_healthy

  ui:
    build:
      context: .
      dockerfile: apps/ui/Dockerfile
    volumes:
      - ./apps/ui:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - VITE_PLC_WS_URL=ws://localhost:3000/ws
    depends_on:
      - runtime

  website:
    build:
      context: .
      dockerfile: apps/website/Dockerfile
    volumes:
      - ./apps/website:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development

  docs:
    build:
      context: .
      dockerfile: docs/Dockerfile
    volumes:
      - ./docs:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development

volumes:
  runtime-data:
  timescaledb-data:
