services:

  runtime:
    build:
      context: apps/runtime
      dockerfile: Dockerfile
      target: builder # Use builder stage for development
    volumes:
      - ./apps/runtime:/app
      - runtime-data:/data
      - go-cache:/root/.cache/go-build
    ports:
      - "3000:3000"  # WebSocket API
      - "2222:2222"  # PLC communication
    environment:
      - GO_ENV=development
      - HYPERDRIVE_DATA_DIR=/data
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_NAME=hyperdrive
      - DB_USER=hyperdrive
      - DB_PASSWORD=hyperdrive
    command: go run ./cmd/hyperdrive/main.go

  ui:
    build:
      context: ./apps/ui
      dockerfile: Dockerfile
    volumes:
      - ./apps/ui:/app
      - pnpm-store:/root/.local/share/pnpm/store
    ports:
      - "5173:5173"  # Vite dev server port
    environment:
      - NODE_ENV=development
      - VITE_WS_URL=ws://localhost:3000/ws
      - VITE_THEIA_URL=http://localhost:3030
    depends_on:
      - runtime
      - theia
    command: sh -c "pnpm install && pnpm dev --host"

  # Theia IDE service
  theia:
    build:
      context: ./apps/theia/browser-app
      dockerfile: Dockerfile
    volumes:
      - ./apps/theia/workspace:/home/project:cached
    ports:
      - "3030:3000"  # Map Theia to port 3030 on host
    restart: unless-stopped

volumes:
  runtime-data:
  go-cache:
  pnpm-store:
