version: '3.8'

services:
  runtime:
    build:
      target: scratch # Use the scratch-based final stage
    volumes:
      - runtime-data:/data
    environment:
      - GO_ENV=production
    restart: unless-stopped
    command: /inrush

  ui:
    build:
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  timescaledb:
    restart: unless-stopped
