package parser

import (
	"github.com/inrush-io/dsl"
)

const (
	TOKEN_NL                 dsl.TokenType = "NL"
	TOKEN_COMMA              dsl.TokenType = "COMMA"
	TOKEN_COMMENT            dsl.TokenType = "COMMENT"
	TOKEN_FUNCTION_BLOCK     dsl.TokenType = "FUNCTION_BLOCK"
	TOKEN_FUNCTION           dsl.TokenType = "FUNCTION"
	TOKEN_PROGRAM            dsl.TokenType = "PROGRAM"
	TOKEN_END_FUNCTION_BLOCK dsl.TokenType = "END_FUNCTION_BLOCK"
	TOKEN_END_FUNCTION       dsl.TokenType = "END_FUNCTION"
	TOKEN_END_PROGRAM        dsl.TokenType = "END_PROGRAM"
	TOKEN_VAR_INPUT          dsl.TokenType = "VAR_INPUT"
	TOKEN_VAR_OUTPUT         dsl.TokenType = "VAR_OUTPUT"
	TOKEN_VAR                dsl.TokenType = "VAR"
	TOKEN_END_VAR            dsl.TokenType = "END_VAR"
	TOKEN_VARIABLE           dsl.TokenType = "VARIABLE"
	TOKEN_LITERAL            dsl.TokenType = "LITERAL"
	TOKEN_COLON              dsl.TokenType = "COLON"
	TOKEN_INT                dsl.TokenType = "INT"
	TOKEN_REAL               dsl.TokenType = "REAL"
	TOKEN_BOOL               dsl.TokenType = "BOOL"
	TOKEN_STRING             dsl.TokenType = "STRING"
	TOKEN_ARRAY              dsl.TokenType = "ARRAY"
	TOKEN_STRUCT             dsl.TokenType = "STRUCT"
	TOKEN_END_STRUCT         dsl.TokenType = "END_STRUCT"
	TOKEN_SEMICOLON          dsl.TokenType = "SEMICOLON"
	TOKEN_ASSIGN             dsl.TokenType = "ASSIGN"
	TOKEN_OPEN_PAREN         dsl.TokenType = "OPEN_PAREN"
	TOKEN_CLOSE_PAREN        dsl.TokenType = "CLOSE_PAREN"
	TOKEN_DOT                dsl.TokenType = "DOT"
	TOKEN_DOTDOT             dsl.TokenType = "DOTDOT"
	TOKEN_OF                 dsl.TokenType = "OF"
	TOKEN_LBRACKET           dsl.TokenType = "LBRACKET"
	TOKEN_RBRACKET           dsl.TokenType = "RBRACKET"
	TOKEN_PLUS               dsl.TokenType = "PLUS"
	TOKEN_MINUS              dsl.TokenType = "MINUS"
	TOKEN_MULTIPLY           dsl.TokenType = "MULTIPLY"
	TOKEN_DIVIDE             dsl.TokenType = "DIVIDE"
	TOKEN_AND                dsl.TokenType = "AND"
	TOKEN_OR                 dsl.TokenType = "OR"
	TOKEN_NOT                dsl.TokenType = "NOT"
	TOKEN_GT                 dsl.TokenType = "GT"
	TOKEN_LT                 dsl.TokenType = "LT"
	TOKEN_GE                 dsl.TokenType = "GE"
	TOKEN_LE                 dsl.TokenType = "LE"
	TOKEN_EQ                 dsl.TokenType = "EQ"
	TOKEN_NE                 dsl.TokenType = "NE"
	TOKEN_IF                 dsl.TokenType = "IF"
	TOKEN_THEN               dsl.TokenType = "THEN"
	TOKEN_ELSIF              dsl.TokenType = "ELSIF"
	TOKEN_ELSE               dsl.TokenType = "ELSE"
	TOKEN_END_IF             dsl.TokenType = "END_IF"
	TOKEN_FOR                dsl.TokenType = "FOR"
	TOKEN_TO                 dsl.TokenType = "TO"
	TOKEN_BY                 dsl.TokenType = "BY"
	TOKEN_DO                 dsl.TokenType = "DO"
	TOKEN_END_FOR            dsl.TokenType = "END_FOR"
	TOKEN_WHILE              dsl.TokenType = "WHILE"
	TOKEN_END_WHILE          dsl.TokenType = "END_WHILE"
	TOKEN_REPEAT             dsl.TokenType = "REPEAT"
	TOKEN_UNTIL              dsl.TokenType = "UNTIL"
	TOKEN_END_REPEAT         dsl.TokenType = "END_REPEAT"
)
